In [1]:
import pandas as pd
import numpy as np

In [2]:
features = pd.read_csv('example_data/prep_data.csv')

In [3]:
train_small = pd.read_csv('example_data/train_small.csv')

In [4]:
test_small = pd.read_csv('example_data/test_small.csv')

In [5]:
full_training = pd.merge(train_small, features, on= 'anime_id')

In [6]:
full_training.drop('Unnamed: 0', inplace=True, axis =1)

In [7]:
full_test = pd.merge(test_small, features, on='anime_id')


In [8]:
full_test.drop('Unnamed: 0', inplace=True, axis =1)

In [18]:
full_training.to_csv('example_data/full_training.csv')

In [19]:
full_test.to_csv('example_data/full_test.csv')

In [9]:
full_training.sort_values('user_id', inplace=True)
full_test.sort_values('user_id', inplace=True)

In [10]:
full_training.to_csv('example_data/full_training.csv')
full_test.to_csv('example_data/full_test.csv')

In [11]:
full_training.head()

user_id  anime_id  rating  episodes  popularity  duration_min
24990        9       603       9        49        2470          24.0
8406         9       813      10       291          70          24.0
2467         9      1535      10        37           1          23.0
11936        9      3455       0        26         186          24.0
17117        9      5460       0         1        2137         111.0

In [12]:
def get_data(df):
	#f = open(file_loc, 'r')
	data = []
	for line in df.index.values:
		new_arr = []
		
		score = df.loc[line, 'rating']
		q_id = df.loc[line, 'user_id']
		new_arr.append(int(score))
		new_arr.append(int(q_id))
		arr = list(df.loc[line, ['episodes', 'popularity', 'duration_min']])
		#print("subseted arr is:", arr)
		for el in arr:
			new_arr.append(float(el))
		#print(" \n New arr is:",new_arr)
		data.append(new_arr)
	#f.close()
	print(np.array(data))
	return np.array(data)	

In [13]:
training_data = get_data(full_training)

[[9.00000e+00 9.00000e+00 4.90000e+01 2.47000e+03 2.40000e+01]
 [1.00000e+01 9.00000e+00 2.91000e+02 7.00000e+01 2.40000e+01]
 [1.00000e+01 9.00000e+00 3.70000e+01 1.00000e+00 2.30000e+01]
 ...
 [1.00000e+01 2.82985e+05 1.00000e+00 1.71800e+03 1.04000e+02]
 [0.00000e+00 2.82985e+05 1.30000e+01 2.24000e+02 2.30000e+01]
 [0.00000e+00 2.82985e+05 1.00000e+00 2.93300e+03 2.80000e+01]]


In [41]:
#list(full_training.loc[24990, ['episodes', 'popularity', 'duration_min']])

In [42]:
#full_training.index.values

In [15]:
from lambdamart import LambdaMART

In [16]:
model = LambdaMART(
	training_data=training_data, 
	number_of_trees=2, 
	learning_rate=0.1)

In [2]:
#model.fit()

In [48]:
full_training['user_id'].nunique()

4615

In [1]:
#average_ndcg, predicted_scores = model.validate(test_data,5)

In [50]:
average_ndcg

0.7269762641801752

In [51]:
predicted_scores = model.predict(test_data[:,1:])

In [53]:
predicted_scores.shape

(26896,)

In [54]:
test_data.shape

(26896, 5)

In [23]:
full_test[full_test['user_id'] == 280842]

index  user_id  anime_id  rating  episodes  popularity  duration_min
26669  11218   280842       122       9        52        1158          24.0
26670   3933   280842       853       0        26          69          23.0
26671   1409   280842       431       0         1          89         117.0
26672   1823   280842       269       0       366          18          24.0
26673   1584   280842      5262       0        51        1173          24.0
26674   9379   280842        48       0        26         650          24.0
26675   7899   280842      4722       0        25         488          24.0

In [20]:
full_test.reset_index(inplace=True)

In [11]:
test_data2 = full_test[['rating','anime_id','user_id','episodes', 'popularity', 'duration_min' ]]
train_data2 = full_training[['rating','anime_id','user_id','episodes', 'popularity', 'duration_min']]

In [12]:
train_data2.head()

rating  anime_id  user_id  episodes  popularity  duration_min
24990       9       603        9        49        2470          24.0
8406       10       813        9       291          70          24.0
2467       10      1535        9        37           1          23.0
11936       0      3455        9        26         186          24.0
17117       0      5460        9         1        2137         111.0

In [13]:
test_data2.head()

rating  anime_id  user_id  episodes  popularity  duration_min
13182       9       239        9        24         634          24.0
15919       8       142        9        44        1885          24.0
15695      10       223        9       153          99          24.0
11369      10       235        9         0         515          25.0
10361      10        21        9         0          35          24.0

In [14]:
from lambdamart import LambdaMART
import numpy as np


def get_data(df):
	#f = open(file_loc, 'r')
	data = []
	for line in df.index.values:
		new_arr = []
		
		score = df.loc[line, 'rating']
		q_id = df.loc[line, 'user_id']
		new_arr.append(int(score))
		new_arr.append(int(q_id))
		arr = list(df.loc[line, ['episodes', 'popularity', 'duration_min']])
		#print("subseted arr is:", arr)
		for el in arr:
			new_arr.append(float(el))
		#print(" \n New arr is:",new_arr)
		data.append(new_arr)
	#f.close()
	print(np.array(data))
	return np.array(data)	

In [15]:
training_data_reco = get_data(train_data2)
test_data_reco = get_data(test_data2)

[[9.00000e+00 9.00000e+00 4.90000e+01 2.47000e+03 2.40000e+01]
 [1.00000e+01 9.00000e+00 2.91000e+02 7.00000e+01 2.40000e+01]
 [1.00000e+01 9.00000e+00 3.70000e+01 1.00000e+00 2.30000e+01]
 ...
 [1.00000e+01 2.82985e+05 1.00000e+00 1.71800e+03 1.04000e+02]
 [0.00000e+00 2.82985e+05 1.30000e+01 2.24000e+02 2.30000e+01]
 [0.00000e+00 2.82985e+05 1.00000e+00 2.93300e+03 2.80000e+01]]
[[9.00000e+00 9.00000e+00 2.40000e+01 6.34000e+02 2.40000e+01]
 [8.00000e+00 9.00000e+00 4.40000e+01 1.88500e+03 2.40000e+01]
 [1.00000e+01 9.00000e+00 1.53000e+02 9.90000e+01 2.40000e+01]
 ...
 [0.00000e+00 2.82985e+05 1.30000e+01 1.09900e+03 2.50000e+01]
 [7.00000e+00 2.82985e+05 1.30000e+01 4.19000e+02 2.40000e+01]
 [0.00000e+00 2.82985e+05 1.10000e+01 1.45800e+03 2.30000e+01]]


In [16]:
training_data_reco

array([[9.00000e+00, 9.00000e+00, 4.90000e+01, 2.47000e+03, 2.40000e+01],
       [1.00000e+01, 9.00000e+00, 2.91000e+02, 7.00000e+01, 2.40000e+01],
       [1.00000e+01, 9.00000e+00, 3.70000e+01, 1.00000e+00, 2.30000e+01],
       ...,
       [1.00000e+01, 2.82985e+05, 1.00000e+00, 1.71800e+03, 1.04000e+02],
       [0.00000e+00, 2.82985e+05, 1.30000e+01, 2.24000e+02, 2.30000e+01],
       [0.00000e+00, 2.82985e+05, 1.00000e+00, 2.93300e+03, 2.80000e+01]])

In [17]:
model = LambdaMART(
	training_data=training_data_reco, 
	number_of_trees=2, 
	learning_rate=0.1)
model.fit()

lenght of idcg 4615
Tree 0
Tree 1


In [18]:
average_ndcg, predicted_scores = model.validate(test_data_reco,5)

C:\UTA_Acads\FALL_SEMESTER\APM\Anime_Recommendation\LambdaMart\lambdamart.py:332: RuntimeWarning: invalid value encountered in double_scalars
  ndcg_val = (dcg_val / idcg_val)


Mean taken


In [19]:
average_ndcg

0.7269762641801752

In [20]:
train_data2.head()

rating  anime_id  user_id  episodes  popularity  duration_min
24990       9       603        9        49        2470          24.0
8406       10       813        9       291          70          24.0
2467       10      1535        9        37           1          23.0
11936       0      3455        9        26         186          24.0
17117       0      5460        9         1        2137         111.0

In [21]:
np.array(train_data2)

array([[9.00000e+00, 6.03000e+02, 9.00000e+00, 4.90000e+01, 2.47000e+03,
        2.40000e+01],
       [1.00000e+01, 8.13000e+02, 9.00000e+00, 2.91000e+02, 7.00000e+01,
        2.40000e+01],
       [1.00000e+01, 1.53500e+03, 9.00000e+00, 3.70000e+01, 1.00000e+00,
        2.30000e+01],
       ...,
       [1.00000e+01, 8.75000e+02, 2.82985e+05, 1.00000e+00, 1.71800e+03,
        1.04000e+02],
       [0.00000e+00, 3.39000e+02, 2.82985e+05, 1.30000e+01, 2.24000e+02,
        2.30000e+01],
       [0.00000e+00, 1.13550e+04, 2.82985e+05, 1.00000e+00, 2.93300e+03,
        2.80000e+01]])

In [22]:
training_data_reco

array([[9.00000e+00, 9.00000e+00, 4.90000e+01, 2.47000e+03, 2.40000e+01],
       [1.00000e+01, 9.00000e+00, 2.91000e+02, 7.00000e+01, 2.40000e+01],
       [1.00000e+01, 9.00000e+00, 3.70000e+01, 1.00000e+00, 2.30000e+01],
       ...,
       [1.00000e+01, 2.82985e+05, 1.00000e+00, 1.71800e+03, 1.04000e+02],
       [0.00000e+00, 2.82985e+05, 1.30000e+01, 2.24000e+02, 2.30000e+01],
       [0.00000e+00, 2.82985e+05, 1.00000e+00, 2.93300e+03, 2.80000e+01]])

In [23]:
x = [1,2]

In [ ]:
from multiprocessing import Pool
p = Pool()

def f(x):
    return x*7

p.map(f, [1,2,3])